### PR TITLE
feat(copr): expose `module_hotfixes` project setting in service

### PR DESCRIPTION
**Pull request by evgeni**
service part of https://github.com/packit/packit/pull/1829

TODO:

- [x] Update doc-strings where appropriate.
- [x] Update or write new documentation in `packit/packit.dev`: https://github.com/packit/packit.dev/pull/590

Fixes

Related to https://github.com/packit/packit/pull/1829

Merge before/after

---

RELEASE NOTES BEGIN
￼
RELEASE NOTES END

### CODE REVIEW

**Review by jpopelka — APPROVED** [review]

**Review by FrNecas — APPROVED** [review]

**Comment by FrNecas** [comment]
recheck

**Comment by FrNecas** [comment]
recheck

**Comment by FrNecas** [comment]
regate

**Comment by FrNecas** [comment]
Oh god, what is happening today. Looks like some flake, let's retry

**Comment by evgeni** [comment]
Quality testing your CI 😅

**Pull request merged**
