### PR TITLE
Fix searching for base build when triggering OpenScanHub scan

### PR DESCRIPTION
**Pull request by nforro**
Fixes https://github.com/packit/packit-service/issues/2495.

Two notes:
- I'm not sure what are the performance implications of enabling `require_git_repo_in_local_project`
- In case there are no successful builds but there are a lot of commits it could take a while before it fails, however I'm not sure how to detect such case

### CODE REVIEW

**Comment by lbarcziova** [comment]
> I'm not sure what are the performance implications of enabling require_git_repo_in_local_project

it means now for the copr build handler tasks, the git repo would be cloned, which we tried to avoid previously :/ do you think we could solve this in another way?

**Comment by nforro** [comment]
> it means now for the copr build handler tasks, the git repo would be cloned, which we tried to avoid previously :/ do you think we could solve this in another way?

I suppose it would be possible (though a bit hacky) to only enable `require_git_repo_in_local_project` per instance and rebuild `LocalProject`, would that make sense?

**Comment by lbarcziova** [comment]
I am still not sure we should be cloning the whole repo to get few commit hashes, what about getting it via API?

**Comment by mfocko** [comment]
Wouldn't it be easier to get last successful build? From the practical PoV I don't really see a difference between:
* checking commit by commit for a build
* taking last successful build

Or is the issue with different packages in the Copr repo? Can't we just filter by the package name in that case?

**Comment by nforro** [comment]
I think the problem is we need to get only builds triggered from the target branch of a PR. Although it would be weird to build in the same Copr project from different branches, it is possible.

**Comment by nforro** [comment]
I have opened https://github.com/packit/ogr/pull/857.

**Comment by nforro** [comment]
I decided to leave `target_branch_head_commit` there and use it first, since it should work in most cases and `get_commits()` could take some time, so it makes sense to call it only if necessary.

**Comment by lachmanfrantisek** [comment]
> I think the problem is we need to get only builds triggered from the target branch of a PR. Although it would be weird to build in the same Copr project from different branches, it is possible.

We can use Build directories for this purpose. But this would require quite a lot of work.

**Comment by nforro** [comment]
> We can use Build directories for this purpose. But this would require quite a lot of work.

Are you referring to [this](https://github.com/fedora-copr/copr/blob/main/doc/user_documentation.rst#subprojects)? I like the idea of having commit/release triggered builds in a project and PR builds in its subdirectories (I'm just starting to work on https://github.com/packit/packit-service/issues/2432), but I'm not sure if we should force users do configure that if they want to use OSH. Or maybe I just don't get your comment :slightly_smiling_face:

**Review by lbarcziova — APPROVED** [review]
lgtm :+1:

**Pull request merged**
