### PR TITLE
utilize get_valid_build_targets from packit.copr_helper

### PR DESCRIPTION
**Pull request by TomasTomecek**
the function was moved to avoid circular dependency

TODO:

- [x] needs to be merged together with https://github.com/packit/packit/pull/1824

---

RELEASE NOTES BEGIN
RELEASE NOTES END

### CODE REVIEW

**Comment by TomasTomecek** [comment]
nope
```
Trying to pull quay.io/packit/packit-service-tests:stg...
```
hit recheck too soon

**Comment by TomasTomecek** [comment]
recheck

**Comment by TomasTomecek** [comment]
`=== 690 passed, 3 warnings in 17.41s ===`

locally

so these were still cached somewhere

**Comment by TomasTomecek** [comment]
recheck

**Comment by TomasTomecek** [comment]
recheck

**Review by lbarcziova — APPROVED** [review]

**Review by majamassarini — APPROVED** [review]

**Pull request merged**
