### PR TITLE
Always allow explicit job/event matching

### PR DESCRIPTION
**Pull request by majamassarini**
Packit config has many other matching jobs,
do not skip the koji-build job just because there are other matching jobs.

related to packit-service#1540

### CODE REVIEW

**Review by lachmanfrantisek — APPROVED** [review]

**Review by lachmanfrantisek — COMMENTED** [review]
Oh, maybe one thing. Can we add this use-case to the tests?

edit: Probably here: https://github.com/packit/packit-service/blob/main/tests/unit/test_jobs.py

**Comment by majamassarini** [comment]
> Oh, maybe one thing. Can we add this use-case to the tests?
> 
> edit: Probably here: https://github.com/packit/packit-service/blob/main/tests/unit/test_jobs.py

The test already exists: https://github.com/packit/packit-service/blob/main/tests/unit/test_jobs.py#L2362

With the previous version of the code one more test was needed to catch the problem I met today. With this new version of the code this is the only needed test, I think :-).

**Comment by lachmanfrantisek** [comment]
I meant the test for the use-case covered by this PR (so it fails before this change and successes after it).

So, exactly what you had in the description: `Packit config has many other matching jobs, do not skip the koji-build job just because there are other matching jobs.`

**Review by lbarcziova — APPROVED** [review]

**Comment by majamassarini** [comment]
recheck

**Pull request merged**
