### PR TITLE
New version of decorators in requre

### PR DESCRIPTION
**Pull request by jscotka**

### CODE REVIEW

**Review by jpopelka — APPROVED** [review]
LGTM but I'd like Franta to have another look.

**Review by lachmanfrantisek — APPROVED** [review]
Looks good to me. Thanks!

**Comment by lachmanfrantisek** [comment]
btw, is it still WIP?

**Comment by jscotka** [comment]
> btw, is it still WIP?

@lachmanfrantisek yep, forgot to remove it, but i've found that I had generation of tmpfiles ouside of requre so that tempfile everytimes changes, what was bas from git view, now I've just done property from self.tempfile so that now it is fixed and tempfile will not change everytime filename. I found it yesterday evening when playiing with copr tests :-)

**Review by lachmanfrantisek — APPROVED** [review]

**Pull request merged**
