### PR TITLE
Parse multi part namespaces in event parsing

### PR DESCRIPTION
**Pull request by lachmanfrantisek**
- Use url parsing from OGR to support more complicated scenarios like multi-part namespaces.
- Rename `https_url` Event property to `project_url` for consistency.

### CODE REVIEW

**Review by csomh — COMMENTED** [review]
Please also add a test to see that all these code paths work with project urls which have 2 or more components in the namespace part.

And update the second commit message to meet the commit message guidelines we are referencing in our contribution guide. The current subject line is longer than 72 characters and GitHub already truncates it.

image

**Comment by lachmanfrantisek** [comment]
> Please also add a test to see that all these code paths work with project urls which have 2 or more components in the namespace part.

We are only using function from another library that is already tested, but I'll change some example to check that.

> And update the second commit message to meet the commit message guidelines we are referencing in our contribution guide. The current subject line is longer than 72 characters and GitHub already truncates it.

Nothing about that in the Contribution guide and only `50 characters is not a hard limit, just a rule of thumb` in https://chris.beams.io/posts/git-commit/ Nevertheless, I agree that the GitHub truncating is not nice and will fix that.

**Comment by csomh** [comment]
> Nothing about that in the Contribution guide and only `50 characters is not a hard limit, just a rule of thumb` in https://chris.beams.io/posts/git-commit/ Nevertheless, I agree that the GitHub truncating is not nice and will fix that.

Sorry, I though linking that blog post from [Requirements for Pull Requests (PR)](https://github.com/packit/packit-service/blob/68c16609dba0eca38692c4e4017ac7ddffef56d6/CONTRIBUTING.md#requirements-for-pull-requests-pr) makes it part of our guidelines.

**Comment by lachmanfrantisek** [comment]
> Sorry, I though linking that blog post from [Requirements for Pull Requests (PR)](https://github.com/packit/packit-service/blob/68c16609dba0eca38692c4e4017ac7ddffef56d6/CONTRIBUTING.md#requirements-for-pull-requests-pr) makes it part of our guidelines.

I agree. It's a good source.

**Comment by lachmanfrantisek** [comment]
@csomh I've fixed those two points -- PTAL.

**Review by csomh — APPROVED** [review]

**Pull request merged**
