### PR TITLE
/packit test without build improvements - monitoring, avoid not json serializable exc

### PR DESCRIPTION
**Pull request by lbarcziova**
- monitor queued builds needed for tests 
- fix not JSON serializable exc

Related to [#1182](https://github.com/packit/packit-service/issues/1182#issuecomment-895887091)

---

TBD

### CODE REVIEW

**Review by lachmanfrantisek — APPROVED** [review]

**Review by TomasTomecek — APPROVED** [review]
:+1:

**Comment by lbarcziova** [comment]
> /usr/local/lib/python3.9/site-packages/packit/local_project.py:140: in __init__
> self.merge_pr(pr_id)
> ...
>  E       AttributeError: 'MockClass' object has no attribute 'target_branch'

looks related to the recent packit changes

**Comment by mfocko** [comment]
> looks related to the recent packit changes (@mfocko could you take a look please?)

@lbarcziova yep, I had a brief look at the requre and haven't spotted this one, will push fix if it's fine with you

**Comment by mfocko** [comment]
recheck

**Pull request merged**
