### PR TITLE
Deny processing GitLab webhooks without token

### PR DESCRIPTION
**Pull request by mfocko**
Signed-off-by: Matej Focko <mfocko@redhat.com>

### CODE REVIEW

**Comment by mfocko** [comment]
issue with token should be created only once, so I don't expect possibility of spamming; also I haven't noticed new issue when testing

**Review by lachmanfrantisek — COMMENTED** [review]
Would be nice to have some test-case but LGTM otherwise. Thanks, good catch!

**Review by jpopelka — APPROVED** [review]

**Comment by mfocko** [comment]
> Would be nice to have some test-case but LGTM otherwise. Thanks, good catch!

extended, we had tests for valid, invalid secrets/tokens in headers, but not for missing

**Review by lachmanfrantisek — APPROVED** [review]
Thanks!

**Comment by mfocko** [comment]
recheck

**Comment by mfocko** [comment]
recheck

**Review by TomasTomecek — APPROVED** [review]
nice

**Review by jpopelka — APPROVED** [review]
rebase please, CI should be fixed

**Pull request merged**
