### PR TITLE
Remove the `compile()` statement from `regexp_match()`

### LINKED ISSUE #2605: Failed to run the handler: SQL expression for WHERE/HAVING role expected, got <sqlalchemy.dialect...
Sentry Issue: [PCKT-002-PACKIT-SERVICE-8QG](https://red-hat-it.sentry.io/issues/6027573182/?referrer=github_integration)

```
Failed to run the handler: SQL expression for WHERE/HAVING role expected, got <sqlalchemy.dialects.postgresql.psycopg2.PGCompiler_psycopg2 object at 0x7f2945d45be0>.
```

### PR DESCRIPTION
**Pull request by nforro**
Related to https://github.com/packit/packit-service/pull/2596.

Fixes #2605.

### CODE REVIEW

**Review by lbarcziova — APPROVED** [review]
would it be hard to add a testcase for this? (in a followup PR would be ok as well)

**Review by majamassarini — APPROVED** [review]
Should we test it in `tests_openshift/database`? Or are we confident enough?

**Comment by nforro** [comment]
> would it be hard to add a testcase for this? (in a followup PR would be ok as well)

I'm not sure, how would you go about testing this?

**Comment by nforro** [comment]
> Should we test it in `tests_openshift/database`?

I thought we disabled those.



> Or are we confident enough?

We are not :sweat_smile:

**Comment by majamassarini** [comment]
> > Should we test it in `tests_openshift/database`?
 
yes, but I am still running them locally. They are good for catching this kind of bugs. And you need just the postgres container running... but I can run them.

**Comment by nforro** [comment]
I've added some tests and they pass locally, so it seems the fix works.

**Review by lbarcziova — APPROVED** [review]
:pray:

**Pull request merged**
