### PR TITLE
Do not try to download a srpm from a None url

### LINKED ISSUE #2611: TypeError: expected str, bytes or os.PathLike object, not NoneType
Sentry Issue: [PCKT-002-PACKIT-SERVICE-8QV](https://red-hat-it.sentry.io/issues/6030594653/?referrer=github_integration)

```
TypeError: expected str, bytes or os.PathLike object, not NoneType
  File "packit_service/worker/handlers/copr.py", line 363, in run
    OpenScanHubHelper(
  File "packit_service/worker/helpers/open_scan_hub.py", line 76, in handle_scan
    if not (paths := self.download_srpms(directory, base_srpm_model, srpm_model)):
  File "packit_service/worker/helpers/open_scan_hub.py", line 234, in download_srpms
    if (base_srpm_path := download_srpm(base_srpm_model)) is None:
  File "packit_service/worker/helpers/open_scan_hub.py", line 228, in download_srpm
    srpm_path = Path(directory).joinpath(basename(srpm_model.url))
  File "posixpath.py", line 142, in basename
    p = os.fspath(p)
```

### PR DESCRIPTION
**Pull request by majamassarini**
Should fix #2611

If build fails the url can be None.

### CODE REVIEW

**Review by lbarcziova — APPROVED** [review]
:+1:

**Comment by lbarcziova** [comment]
> If build fails the url can be None.

isn't the scan submission done only when the build is succeeded?

**Comment by majamassarini** [comment]
> > If build fails the url can be None.
> 
> isn't the scan submission done only when the build is succeeded?

Yes it is. But I believe this exception is related with taking the base build srpm:
```
"2024-10-30T10:35:42.288119317+00:00 stderr F [2024-10-30 10:35:42,288: INFO/MainProcess] task.run_copr_build_end_handler[789984fc-1085-4b7d-9f84-34882f643eb1] Cleaning up the mess.","2024-10-30T10:35:42.288+0000"
"2024-10-30T10:35:42.287913173+00:00 stderr F [2024-10-30 10:35:42,287: DEBUG/MainProcess] task.run_copr_build_end_handler[789984fc-1085-4b7d-9f84-34882f643eb1] Handling the scan raised an exception: expected str, bytes or os.PathLike object, not NoneType. Skipping as this is only experimental functionality for now.","2024-10-30T10:35:42.287+0000"
"2024-10-30T10:35:42.243105568+00:00 stderr F [2024-10-30 10:35:42,243: DEBUG/MainProcess] task.run_copr_build_end_handler[789984fc-1085-4b7d-9f84-34882f643eb1] Searching for base build for 499c523559d4f2305b8d54dc9a8228c7f3060e89 commit in packit/rpm-software-management-rpmlint-mainline Copr project in our DB. ","2024-10-30T10:35:42.243+0000"
"2024-10-30T10:35:42.239785129+00:00 stderr F [2024-10-30 10:35:42,239: DEBUG/MainProcess] task.run_copr_build_end_handler[789984fc-1085-4b7d-9f84-34882f643eb1] Searching for base build for 6c3a457c47e80a8ae302183cbf50de93b06f75a1 commit in packit/rpm-software-management-rpmlint-mainline Copr project in our DB. ","2024-10-30T10:35:42.239+0000"
"2024-10-30T10:35:42.236548175+00:00 stderr F [2024-10-30 10:35:42,236: DEBUG/MainProcess] task.run_copr_build_end_handler[789984fc-1085-4b7d-9f84-34882f643eb1] Searching for base build for 1ba4bd0f97746719281dd981868aa4c8779b9259 commit in packit/rpm-software-management-rpmlint-mainline Copr project in our DB. ","2024-10-30T10:35:42.236+0000"
"2024-10-30T10:35:42.232521672+00:00 stderr F [2024-10-30 10:35:42,232: DEBUG/MainProcess] task.run_copr_build_end_handler[789984fc-1085-4b7d-9f84-34882f643eb1] Searching for base build for b1a8a4227f12bc2179a7f171b52c759468edd7d9 commit in packit/rpm-software-management-rpmlint-mainline Copr project in our DB. ","2024-10-30T10:35:42.232+0000"
"2024-10-30T10:35:42.229330296+00:00 stderr F [2024-10-30 10:35:42,229: DEBUG/MainProcess] task.run_copr_build_end_handler[789984fc-1085-4b7d-9f84-34882f643eb1] Searching for base build for fafbe32a3e848489974bb450c5eb321693cb5983 commit in packit/rpm-software-management-rpmlint-mainline Copr project in our DB. ","2024-10-30T10:35:42.229+0000"
"2024-10-30T10:35:42.226428253+00:00 stderr F [2024-10-30 10:35:42,226: DEBUG/MainProcess] task.run_copr_build_end_handler[789984fc-1085-4b7d-9f84-34882f643eb1] Searching for base build for 022e9cb13898e1240fcaa098b8b135db11a27f68 commit in packit/rpm-software-management-rpmlint-mainline Copr project in our DB. ","2024-10-30T10:35:42.226+0000"
"2024-10-30T10:35:42.222826371+00:00 stderr F [2024-10-30 10:35:42,222: DEBUG/MainProcess] task.run_copr_build_end_handler[789984fc-1085-4b7d-9f84-34882f643eb1] Searching for base build for 84d70576a903b474f7607fb93788b42c1700d3a3 commit in packit/rpm-software-management-rpmlint-mainline Copr project in our DB. ","2024-10-30T10:35:42.222+0000"
"2024-10-30T10:35:42.218780609+00:00 stderr F [2024-10-30 10:35:42,218: DEBUG/MainProcess] task.run_copr_build_end_handler[789984fc-1085-4b7d-9f84-34882f643eb1] Searching for base build for a40f75d6a8c2b8906c1e4469d19051edbbc52165 commit in packit/rpm-software-management-rpmlint-mainline Copr project in our DB. ","2024-10-30T10:35:42.218+0000"
"2024-10-30T10:35:42.215745435+00:00 stderr F [2024-10-30 10:35:42,215: DEBUG/MainProcess] task.run_copr_build_end_handler[789984fc-1085-4b7d-9f84-34882f643eb1] Searching for base build for ca7812204d922b2f34f826e203344f7d6e295fa5 commit in packit/rpm-software-management-rpmlint-mainline Copr project in our DB. ","2024-10-30T10:35:42.215+0000"
"2024-10-30T10:35:42.212846996+00:00 stderr F [2024-10-30 10:35:42,212: DEBUG/MainProcess] task.run_copr_build_end_handler[789984fc-1085-4b7d-9f84-34882f643eb1] Searching for base build for 518f53400d08c82c0f96937ede78c6d17dca89df commit in packit/rpm-software-management-rpmlint-mainline Copr project in our DB. ","2024-10-30T10:35:42.212+0000"
[...]
```

**Comment by lbarcziova** [comment]
@majamassarini ah I see, makes sense, thanks for the explanation!

**Pull request merged**
