### PR TITLE
Move events from service/ to worker/

### PR DESCRIPTION
**Pull request by jpopelka**
The events were initially created in #54 by Rado,
so I can't ask why they were added to service/ while parser was added to worker/.

But I don't see why they should be in service/ when they're not used anywhere there.

### CODE REVIEW

**Comment by jpopelka** [comment]
@lachmanfrantisek @lbarcziova you probably know that code best, let me know what do you think, thanks.

**Comment by jpopelka** [comment]
recheck

**Review by lbarcziova — APPROVED** [review]
+1, it should be in worker/, thanks!

**Review by lachmanfrantisek — COMMENTED** [review]
:+1:

**Pull request merged**
