### PR TITLE
no hardcoded mapping

### PR DESCRIPTION
**Pull request by lachmanfrantisek**
- Do not hardcode mapping from event to job.
- Fixes: #789

### CODE REVIEW

**Comment by lachmanfrantisek** [comment]
recheck

**Comment by lachmanfrantisek** [comment]
recheck

**Review by TomasTomecek — APPROVED** [review]
I yield to tests and stg

**Comment by lachmanfrantisek** [comment]
I've added a `TODO` comment for mapping from issue comments that needs to be solved properly in the future. (For now, we have `issue -> propose-update`, but we need to make it general.)

**Comment by lachmanfrantisek** [comment]
@jscotka I've skipped the test so we can use zuul for merging.

**Pull request merged**
