### PR TITLE
Align with packit#1357 code

### PR DESCRIPTION
**Pull request by majamassarini**
Syncing of default files can now be disabled

Fixes packit/packit#1357

Merge after packit/packit#1483

### CODE REVIEW

**Comment by csomh** [comment]
I see occurrences of `synced_files` in 

```
tests/unit/test_steve.py
tests/unit/test_config.py
tests/unit/test_events.py
tests/integration/test_pr_comment.py
tests/integration/test_koji_build.py
tests/integration/test_bodhi_update.py
tests/integration/test_dg_commit.py
tests/integration/test_check_rerun.py
tests/integration/test_issue_comment.py
tests/integration/test_release_event.py
```

Should those be updated, too?

**Comment by majamassarini** [comment]
This are occurrences of synced_files inside spec files which are yet allowed even if deprecated. I have not modified all those occurrences in tests neither here or in packit code. But if you think it should be done I can do it.

**Comment by csomh** [comment]
> This are occurrences of synced_files inside spec files which are yet allowed even if deprecated. I have not modified all those occurrences in tests neither here or in packit code. But if you think it should be done I can do it.

I see. No there is no need for it for now. Thank you for the explanation!

**Review by csomh — APPROVED** [review]

**Comment by majamassarini** [comment]
recheck

**Pull request merged**
