### PR TITLE
[TF, tmt context] there's no epel distro, but centos

### PR DESCRIPTION
**Pull request by jpopelka**
https://github.com/packit/packit-service/pull/1008#issuecomment-789574614

### CODE REVIEW

**Review by mfocko — APPROVED** [review]
lgtm :)

**Comment by psss** [comment]
Thanks, looks good, looking forward... :)

**Comment by thrix** [comment]
:rocket:

**Comment by psss** [comment]
The epel/centos mapping now [works](http://artifacts.dev.testing-farm.io/317c3b83-246e-4727-8fd0-48ee9092491f/work-featuresidl0GP/log.txt) as expected. Thanks for the quick fix!

**Pull request merged**
