### PR TITLE
Raise Exception for triggering celery autoretries

### PR DESCRIPTION
**Pull request by majamassarini**
If `autoretry_for` some Exceptions is not specified then
celery autoretries are not used
and `retry_backoff` and `retry_backoff_max`
are ignored.

Fixes packit/packit#1450

### CODE REVIEW

**Review by lbarcziova — COMMENTED** [review]
nice idea! would it make sense to create a specific exception for this?

I know it's hard to write tests for this, were you able to test it locally in the end?

**Comment by majamassarini** [comment]
> nice idea! would it make sense to create a specific exception for this?

Ok

> I know it's hard to write tests for this, were you able to test it locally in the end?

Yes, I have somehow reproduced it locally
```python
from celery import Celery, Task
from celery.utils.log import get_task_logger

host = "localhost"
port = "6379"
broker_url = f"redis://{host}:{port}/0"
backend_url = f"redis://{host}:{port}/1"

logger = get_task_logger(__name__)

app = Celery('retry_app', broker=broker_url, backend=backend_url)

@app.task(name='print_hello',
    bind=True,
    autoretry_for=(Exception, ),
    retry_backoff=1,
    retry_backoff_max=32,
    max_retries=14,
    retry_jitter=False,
)
def print_hello(self):
    logger.error("hello world")
    raise Exception

if __name__ == "__main__":
    result = print_hello.apply_async()
    str = result.get(timeout=32)
    print(str)
```

If the `raise Exception` is substituted with the `self.retry` (and `autoretry_for` is not specified) then the `retry_backoff` values are not used. Instead it is used a standard 180s value. For this reason I am quite confident that this change will made the trick.

**Review by lbarcziova — APPROVED** [review]
thanks!

**Review by jpopelka — COMMENTED** [review]
Good catch :rocket:

**Pull request merged**
