### PR TITLE
[Testing, ignore] update Zuul node before packit-service-tests-requre

### PR DESCRIPTION
**Pull request by jpopelka**
Related to all recently failed tests

### CODE REVIEW

**Comment by jpopelka** [comment]
```
| test-node | Dependencies resolved
| test-node | Nothing to do.
```

**Comment by jpopelka** [comment]
nope, still `Request failed: <urlopen error _ssl.c:1106: The handshake operation timed out>`

**Comment by TomasTomecek** [comment]
Whaaaaaaaaaaaat, this is our 1000th PR/issue?

congrats @jpopelka :P

**Comment by lachmanfrantisek** [comment]
> Whaaaaaaaaaaaat, this is our 1000th PR/issue?

This one needs to be merged!

**Comment by jpopelka** [comment]
rather ack #1003, please

**Pull request closed without merging**
