### PR TITLE
fix(tests): account for enable_net=False default

### PR DESCRIPTION
**Pull request by TomasTomecek**
TODO:

- [x] Write new tests or update the old ones to cover new functionality.

Needs: https://github.com/packit/packit/pull/1825

Release notes present in the Packit PR.

### CODE REVIEW

**Comment by TomasTomecek** [comment]
and since the PR is not merged yet, the tests should fail.

**Comment by TomasTomecek** [comment]
o_O
```
tests/unit/test_copr_build.py::test_submit_copr_build[True-True-buildopts0] PASSED                                                                                                                         [ 37%] 
tests/unit/test_copr_build.py::test_submit_copr_build[False-True-buildopts1] PASSED                                                                                                                        [ 37%]
tests/unit/test_copr_build.py::test_submit_copr_build[True-False-buildopts2] PASSED                                                                                                                        [ 38%] 
tests/unit/test_copr_build.py::test_submit_copr_build[False-False-buildopts3] PASSED                                                                                                                       [ 38%] 
```
locally

**Comment by TomasTomecek** [comment]
oh right, RPMs

**Review by jpopelka — APPROVED** [review]

**Comment by TomasTomecek** [comment]
recheck

**Comment by TomasTomecek** [comment]
no clue honestly: pre-commit passes for me locally & the PR is rebased

**Comment by TomasTomecek** [comment]
regate

**Pull request merged**
