### PR TITLE
Add disclaimer regarding removal of :champagne: comment

### LINKED ISSUE #881: Include warning about our plans to disable the "Congratulations" comments in this comment
Update the content of comment about successfully created Copr build:
- [ ] add a warning about our plan to disable these comments in 2 weeks
- [ ] add a note that users can reach out to us if they would really like to receive these comments

### PR DESCRIPTION
**Pull request by mfocko**
Closes #881

Signed-off-by: Matej Focko <mfocko@redhat.com>

### CODE REVIEW

**Review by jpopelka — APPROVED** [review]

**Review by lachmanfrantisek — COMMENTED** [review]
Nice, what about linking this or the other issue?

**Comment by mfocko** [comment]
> Nice, what about linking this or the other issue?

I thought about this, but since we "smack" the comment on every PR, I can see the issue being spammed just by use referencing it. If it's not a big problem, could be added. :)

**Comment by lachmanfrantisek** [comment]
> I thought about this, but since we "smack" the comment on every PR, I can see the issue being spammed just by use referencing it. If it's not a big problem, could be added. :)

Good point. Let's go without that.

**Review by lachmanfrantisek — APPROVED** [review]

**Comment by mfocko** [comment]
> > I thought about this, but since we "smack" the comment on every PR, I can see the issue being spammed just by use referencing it. If it's not a big problem, could be added. :)
> 
> Good point. Let's go without that.

We could probably pin the issue for removal of it?

**Pull request merged**
