### PR TITLE
Configure new base image in Dockerfile's

### PR DESCRIPTION
**Pull request by sakalosj**
New base image with generic depndencies is configured as base in our
existing Dockerfile's.

Depends on https://github.com/packit/deployment/pull/111

### CODE REVIEW

**Comment by sakalosj** [comment]
recheck

**Comment by sakalosj** [comment]
recheck

**Comment by sakalosj** [comment]
recheck

**Comment by sakalosj** [comment]
recheck

**Comment by sakalosj** [comment]
recheck

**Comment by TomasTomecek** [comment]
I'm opting out of the review process since I wasn't involved in this much.

**Pull request merged**
