### PR TITLE
Post comment as feedback for /packit koji-tag

### LINKED ISSUE #2552: There is no feedback for `/packit koji-tag` command
There is no pipeline for this, so users can't check the dashboard, and for some reason there is no `The task was accepted` PR comment. The text of the comment could say something like `Tagging of ${NVR} into ${SIDETAG} has been successfully requested`.

### PR DESCRIPTION
**Pull request by lbarcziova**
Fixes #2552

I did not include any specific details about the requested tagging, as the feedback should be quick and to stay consistent with other feedback comments. 

I would link some interface where users could watch the activity, but not sure if there is anything like that (like a specific Koji subpage), @nforro do you have any suggestions?

RELEASE NOTES BEGIN

N/A

RELEASE NOTES END

### CODE REVIEW

**Comment by nforro** [comment]
> I would link some interface where users could watch the activity, but not sure if there is anything like that (like a specific Koji subpage), @nforro do you have any suggestions?

There is a Koji task for tagging - [example](https://koji.fedoraproject.org/koji/taskinfo?taskID=124216699). Task ID should be returned from [`tagBuild()`](https://github.com/packit/packit/blob/7e44ad8708cd4c680aabcaa0aa8ba4218195ebe3/packit/utils/koji_helper.py#L359).

**Review by nforro — APPROVED** [review]
:pray:

**Comment by nforro** [comment]
> > I would link some interface where users could watch the activity, but not sure if there is anything like that (like a specific Koji subpage), @nforro do you have any suggestions?
> 
> There is a Koji task for tagging - [example](https://koji.fedoraproject.org/koji/taskinfo?taskID=124216699). Task ID should be returned from [`tagBuild()`](https://github.com/packit/packit/blob/7e44ad8708cd4c680aabcaa0aa8ba4218195ebe3/packit/utils/koji_helper.py#L359).

I'm not sure if it's possible to implement without storing the ID somewhere. Should I open an issue about this?

**Comment by lbarcziova** [comment]
@nforro I was thinking about storing this info and also displaying it somehow on our dashboard, then we could just link that specific page on our dashboard, WDYT?

**Comment by nforro** [comment]
Sure, that would be the best solution :+1:

**Pull request merged**
