### PR TITLE
Send extra parameters to the TF API

### PR DESCRIPTION
**Pull request by r0x0d**
This PR is a work that follows the first implementation started in the https://github.com/packit/packit/pull/1619

Signed-off-by: Rodolfo Olivieri <rolivier@redhat.com>

TODO:

- [x] Write new tests or update the old ones to cover new functionality.
- [x] Update doc-strings where appropriate.
- [ ] Update or write new documentation in `packit/packit.dev`.

I'm waiting for fix the name with either `tf_name` or `tmt_plan` based on this discussion https://github.com/packit/packit-service/issues/1507#issuecomment-1154177501

Fixes https://github.com/packit/packit-service/issues/1534

Related to https://github.com/packit/packit/pull/1619

Merge after https://github.com/packit/packit/pull/1619

---

### CODE REVIEW

**Comment by TomasTomecek** [comment]
shall we help in any way here?

**Comment by r0x0d** [comment]
Hey! I was waiting for a review and to see if there's anything else missing for this PR. 

For me, it looks like it is mostly done, only this test problem that is failing, but I believe it was because of the other PR that was not merged when the tests ran.

**Review by TomasTomecek — APPROVED** [review]
LGTM

anyone else wants to have a look?

**Comment by TomasTomecek** [comment]
recheck

**Comment by TomasTomecek** [comment]
please rebase and we can merge :)

**Review by lachmanfrantisek — APPROVED** [review]
:+1: Thanks a lot!

**Review by FrNecas — APPROVED** [review]
LGTM

**Comment by r0x0d** [comment]
I will rebase right now! Thanks guys.

**Pull request merged**
